---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: centos/stream8
    config_options:
      disksize.size: "'52GB'"
provisioner:
  name: ansible
verifier:
  name: ansible
