---
- name: Create a docker partition at least of 40GB and install it
  hosts: docker_swarm_manager, docker_swarm_worker
  become: true
  tasks:
      - name: Enable Docker daemon at startup
        service:
            name: docker
            state: started
            enabled: true
  roles:
      - partition
      - ansible-role-docker-ce

- name: Expose Docker Daemon REST API
  hosts: docker_swarm_manager, docker_swarm_worker
  roles:
      - role: docker-remote-api
        docker_remote_client_use_certs_as_default: true
        docker_remote_client_become: true

- name: Docker Swarm setup
  hosts: docker_swarm_manager, docker_swarm_worker
  become: true
  roles:
      - docker-swarm
  vars:
      docker_swarm_interface: eth1

- name: Deploy service from localhost to Docker Swarm cluster
  hosts: localhost
  tasks:
      - name: Create a test service
          shell: docker service create --replicas 1 -p 80:80 --name web1 nginx
          environment:
            DOCKER_HOST: "tcp://192.168.56.20:2376"
            DOCKER_TLS_VERIFY: 1
          register: docker_stack_deploy_result
  - debug:
      var: docker_stack_deploy_result
